INSERT INTO categories(category_name, createdAt, updatedAt) VALUES("Tops", NOW(), NOW()); 
INSERT INTO categories(category_name, createdAt, updatedAt) VALUES("Jeans", NOW(), NOW()); 
INSERT INTO categories(category_name, createdAt, updatedAt) VALUES("Dress", NOW(), NOW()); 
INSERT INTO categories(category_name, createdAt, updatedAt) VALUES("Pants", NOW(), NOW()); 
INSERT INTO categories(category_name, createdAt, updatedAt) VALUES("Shoes", NOW(), NOW()); 
INSERT INTO categories(category_name, createdAt, updatedAt) VALUES("Handbags", NOW(), NOW()); 
INSERT INTO categories(category_name, createdAt, updatedAt) VALUES("Accessories", NOW(), NOW()); 
INSERT INTO categories(category_name, createdAt, updatedAt) VALUES("Skirt", NOW(), NOW()); 
INSERT INTO categories(category_name, createdAt, updatedAt) VALUES("Shorts", NOW(), NOW()); 